[package]
name = "usfx_test"
version = "0.1.1"
edition = "2021"
publish = false
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple program to test USFX lib"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
usfx = "0.1.3"
anyhow = "1.0.63"
pixels-graphics-lib = "0.13.2"
indexmap = "2.1.0"
cpal = "0.14.0"