[package]
name = "usfx_test"
version = "0.2.0"
edition = "2021"
publish = false
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple program to test USFX lib"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
usfx = { version = "0.1.5", features = ["serde"] }
anyhow = "1.0.76"
pixels-graphics-lib = { version="0.13.7", features = ["window_prefs"]}
indexmap = "2.1.0"
cpal = "0.15.2"
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
chrono = { version = "0.4.31", features = ["alloc", "std","clock","serde"]}
env_logger = "0.10.1"
log = "0.4.20"