[package]
name = "usfx_test"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Ray Britton <raybritton@pm.me>"]
description = "Simple program to test USFX lib"
license-file = "LICENSE"

[dependencies]
usfx = "0.1.3"
anyhow = "1.0.63"
pixels-graphics-lib = "0.5.0"
buffer-graphics-lib = "0.2.1"
winit = "0.27.2"
winit_input_helper = "0.13.0"
indexmap = "1.9.1"
cpal = "0.11.0"